name: CI

on:
  push:
    branches: [ "v4.x" ]
  pull_request:
    branches: [ "v4.x" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 8, 11 ]
        os: [ubuntu-latest, windows-latest, mac-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - run: mvn -B install --fail-at-end --no-transfer-progress --file pom.xml
