name: CI

on:
  push:
    branches: [ "v4.x" ]
  pull_request:
    branches: [ "v4.x" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 8, 11 ]
        os: [ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - run: mvn wrapper:wrapper --no-transfer-progress -Dmaven="3.9.5"
      - run: ./mvnw -B install --fail-at-end --no-transfer-progress --file pom.xml
